<a href="https://colab.research.google.com/github/P-yi-6/Data-science-wk1/blob/main/NumpyExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
#1. Create a numpy array of size 2 x 2

import numpy as np

np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [31]:
#2.Create a random numpy array of size 3 x 4

import numpy as np

np.random.rand(3,4)


array([[0.63761884, 0.1049571 , 0.31833237, 0.84690936],
       [0.099385  , 0.99038953, 0.17333217, 0.79982069],
       [0.91000027, 0.56140722, 0.46308811, 0.0465365 ]])

In [47]:
#3. Create a numpy array of ones and a numpy array of zeroes

import numpy as np
shape = (3,4)
array_of_ones = np.ones(shape)
print("Array_of_Ones(3*4):")
print(array_of_ones)

print("-"*16)

array_of_zeros = np.zeros(shape)
print("Array_of_Zeros(3*4):")
print(array_of_zeros)


NameError: name 'size' is not defined

In [49]:
import numpy as np
shape = (6,3)
rand_6x3 = np.random.randint(0, 10, shape)

T_array = rand_6x3.T

print("Original 6x3 Array:")
print(rand_6x3)
print("\nTransposed Array (3x6):")
print(T_array)

Original 6x3 Array:
[[5 1 4]
 [0 9 5]
 [8 0 9]
 [2 6 3]
 [8 2 4]
 [2 6 4]]

Transposed Array (3x6):
[[5 0 8 2 8 2]
 [1 9 0 6 2 6]
 [4 5 9 3 4 4]]


In [62]:
import numpy as np

A = np.random.rand(n, p)

B = np.random.rand(p, m)

dot_product = A @ B